version: '3.8'

services:
    app:
        environment:
            - APP_BASE_URL=https://sub.domain.com
            - APP_PORT=1337
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=joplin
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=db
            - DB_CLIENT=pg
            - VIRTUAL_HOST=sub.domain.com
            - LETSENCRYPT_HOST=sub.domain.com
            - VIRTUAL_PORT=1337

        restart: unless-stopped
        image: joplin/server:latest
        networks:
            - proxy-network
            - backend
        
    db:
        restart: unless-stopped
        image: postgres:13.1
        ports:
            - "5432:5432"
        volumes:
            - joplin-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=joplin
            - POSTGRES_DB=joplin

        networks:
            - backend

volumes:
    joplin-data:

networks:
    proxy-network:
        external: true
    backend:
