version: '3.8'

services:
    vaultwarden:
        image: vaultwarden/server:latest
        container_name: vaultwarden
        restart: always
        depends_on:
            - postgres-db
        env_file:
            - .env
        volumes:
            - ./data:/data
        ports:
            - 8445:80
        networks:
            - vaultwarden
            - reverseproxy-nw

    postgres-db:
        image: postgres:14
        container_name: vaultwarden-postgres
        restart: always
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=vaultwarden
            - POSTGRES_USER=one800
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        networks:
            - vaultwarden

networks:
    vaultwarden:
    reverseproxy-nw:
        external: true


