version: "3.8"

services:

  wg-easy:
    image: "weejewel/wg-easy:latest"
    container_name: wg-easy
    restart: unless-stopped
    environment:
      - WG_HOST=wireguard.thelazyoxymoron.me
      - PASSWORD=${WIREGUARD_PASSWORD}
      - VIRTUAL_HOST=wireguard.thelazyoxymoron.me
      - LETSENCRYPT_HOST=wireguard.thelazyoxymoron.me
      - VIRTUAL_PORT=51821

    ports:
      - "51820:51820/udp"

    volumes:
      - "./wg-easy:/etc/wireguard"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - "proxy-network"
      - "wireguard"

networks:
  proxy-network:
    external: true
  wireguard:

