version: '3.8'

services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    restart: unless-stopped
    command:
      - serve
    volumes:
      - ./cache:/var/cache/ntfy
      - ./ntfy-data:/etc/ntfy
      - ./ntfy-access-db:/var/lib/ntfy
    env_file:
      - .env
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true

