version: '3.8'

services:
    outline_redis:
        image: redis
        restart: always
        container_name: outline_redis
        volumes:
            - ./redis:/var/lib/redis
        networks:
            - outline
            - reverseproxy-nw

    outline_postgres:
        image: postgres:13
        restart: always
        container_name: outline_postgres
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=outline
            - POSTGRES_DB=outline
        volumes:
            - postgres_db:/var/lib/postgresql/data
        networks:
            - outline

    outline_minio:
        image: minio/minio
        restart: always
        container_name: outline_minio
        volumes:
            - ./minio:/data:Z
        environment:
            - MINIO_ROOT_USER=minio
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
            - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL}
        networks:
            - reverseproxy-nw
        command: "server /data --console-address :9001"

    outline:
        image: outlinewiki/outline
        user: root
        restart: always
        container_name: outline
        command: sh -c "yarn sequelize:migrate --env=production-ssl-disabled && yarn start --env=production-ssl-disabled"
        depends_on:
            - outline_postgres
            - outline_redis
            - outline_minio
        environment:
            - PGSSLMODE=disable
            - SECRET_KEY=${SECRET_KEY}
            - UTILS_SECRET=${UTILS_SECRET}
            - DATABASE_URL=postgres://outline:${POSTGRES_PASSWORD}@outline_postgres:5432/outline
            - REDIS_URL=redis://outline_redis:6379
            - URL=${WIKI_URL}
            - PORT=443
            - AWS_ACCESS_KEY_ID=minio
            - AWS_REGION=us-east-1
            - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
            - AWS_S3_UPLOAD_BUCKET_URL=${WIKIDATA_URL}
            - AWS_S3_UPLOAD_BUCKET_NAME=outline
            - AWS_S3_UPLOAD_MAX_SIZE=26214400
            - AWS_S3_FORCE_PATH_STYLE=true
            - AWS_S3_ACL=private
            - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
            - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
            - OIDC_AUTH_URI=${AUTH_URL}/application/o/authorize/
            - OIDC_TOKEN_URI=${AUTH_URL}/application/o/token/
            - OIDC_USERINFO_URI=${AUTH_URL}/application/o/userinfo/
            - OIDC_USERNAME_CLAIM=email
            - OIDC_DISPLAY_NAME=Authentik
            - FORCE_HTTPS=true
            - SMTP_HOST=${SMTP_HOST}
            - SMTP_PORT=587
            - SMTP_USERNAME=${SMTP_USERNAME}
            - SMTP_PASSWORD=${SMTP_PASSWORD}
            - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
            - SMTP_REPLY_EMAIL=${SMTP_REPLY_EMAIL}
            - SMTP_SECURE=true

        networks:
            - outline
            - reverseproxy-nw

networks:
    outline:
    reverseproxy-nw:
        external: true

volumes:
    postgres_db:
