version: '3.8'

services:
    db:
        image: postgres:14.2
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_USER=${PGUSER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - postgres_db:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    postgres_db:
